#Ponemos un alias para hacer referencia a este stage
FROM node:14.17.4-alpine3.14 as build
#Creamos este directorio y nos movemos a él
WORKDIR /Youfavs
#Copiamos el frontend al directorio del contenedor
COPY ../ ./
#Instalamos las dependencias y pasamos a producción
RUN npm i && npm run build --prod

FROM nginx:stable-alpine
#Instalamos bash
RUN apk --no-cache add bash
#Copiamos el directorio del stage anterior al directorio de este stage
COPY --from=build Youfavs/dist/youfavs /var/www/Youfavs
COPY ./nginx/youfavs.com /etc/nginx/conf.d/default.conf